

services:
    app:
        image: localhost:8484/devops/flasked-app:latest
        ports:
            - "5000:5000"
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
